include("$(MPY_DIR)/extmod/uasyncio")
freeze("$(PORT_DIR)/modules")
require("neopixel")
require("ntptime")
freeze("modules")
module("microdot.py", "vendor/microdot/src")
module("microdot_asyncio.py", "vendor/microdot/src")
